#!/usr/bin/env ruby

require_relative "tools"
require_relative "get_data"
require_relative "print_info"

type                        =   "1rPCAC"
url                         =   "https://www.boursorama.com/bourse/action/graph/ws/UpdateCharts?symbol=#{type}"
frequency_in_seconds        =   5
operating_time_in_seconds   =   50
all_data                    =   [type, url, frequency_in_seconds, operating_time_in_seconds]

for i in 1 .. operating_time_in_seconds / frequency_in_seconds
    buffer = get_data(url)
    print_info(buffer, all_data)
    sleep frequency_in_seconds
end
